name: Check win32 compiles

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display build summary
        env:
          OPTION: x64
        working-directory: .
        run: |
          echo Option:$Env:OPTION
          echo "Checkout to $Env:GITHUB_WORKSPACE"

      - name: "Remove builtin vcpkg (old)"
        working-directory: .
        shell: "bash"
        run: |
          rm -rf "$VCPKG_INSTALLATION_ROOT"

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Bootstrap vcpkg"
        working-directory: .
        shell: "bash"
        run: |
          ./vcpkg/bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        working-directory: ./vcpkg
        shell: "bash"
        run: |
          `./vcpkg.exe fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "hpcc-systems" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          `./vcpkg.exe fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json"

      - name: "vcpkg package refresh"
        working-directory: ./vcpkg
        shell: "bash"
        run: >
          ./vcpkg.exe install --keep-going icu zlib openssl libxslt winflexbison --triplet x64-windows

      - name: Windows compilation
        working-directory: .
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 16 2019" -T host=x64 -A x64
          cmake --build . -- -m
